---
- hosts: rpm
  become: yes
  
  tasks:
  
  - name: Software install
    yum:
      name:
        - redhat-lsb-core 
        - rpmdevtools
        - wget
        - gcc
        - nano
        - rpm-build
        - createrepo
        - yum-utils
      state: present
  
  - name: download srpm_nginx
    get_url:
      url: https://nginx.org/packages/centos/7/SRPMS/nginx-1.14.1-1.el7_4.ngx.src.rpm
      dest: /home/vagrant/
      
  - name: download openssl
    get_url:
      url: https://www.openssl.org/source/openssl-1.1.1s.tar.gz
      dest: /home/vagrant/
      validate_certs: false
      
  - name: unzipped openssl
    unarchive:
      src: /home/vagrant/openssl-1.1.1s.tar.gz
      dest: /home/vagrant/  
      remote_src: yes
      
  - name: rpm
    shell: rpm -i nginx-1.14.1-1.el7_4.ngx.src.rpm    
        
  - name: install dependies
    shell: yum-builddep /root/rpmbuild/SPECS/nginx.spec -y
    
  - name: build rpm
    shell: rpmbuild -bb /root/rpmbuild/SPECS/nginx.spec  
    
  - name: install nginx
    yum:
      name: /root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
      state: present 
      
  - name: start nginx
    systemd:
      name: nginx
      state: started
      enabled: yes     
    
  - name: directory for repo
    copy:
      src: /root/rpmbuild/RPMS/x86_64/nginx-1.14.1-1.el7_4.ngx.x86_64.rpm
      dest: /usr/share/nginx/html/repo/
      remote_src: yes
      
  - name: create repo
    yum_repository:
      name: otus
      description: otus-linux
      baseurl: http://localhost/repo
      gpgcheck: no
      enabled: yes  
      
  - name: createrepo
    shell: createrepo /usr/share/nginx/html/repo/    
    
  - name: add RPM ftp
    shell: yumdownloader --source ftp
    
  - name: rpm ftp
    shell: rpm -i ftp-0.17-67.el7.src.rpm  
  
  - name: install dependies ftp
    shell: yum-builddep /root/rpmbuild/SPECS/ftp.spec -y
  
  - name: build rpm ftp
    shell: rpmbuild -bb /root/rpmbuild/SPECS/ftp.spec
    
  - name: add ftp.rpm to repo
    copy:
      src: /root/rpmbuild/RPMS/x86_64/ftp-0.17-67.el7.x86_64.rpm
      dest: /usr/share/nginx/html/repo/
      remote_src: yes
      
  - name: createrepo2
    shell: createrepo /usr/share/nginx/html/repo/   
    
  - name: clean yum
    shell: yum clean all
